const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding UrbanNest database...');

  // Clean existing data
  await prisma.notification.deleteMany();
  await prisma.message.deleteMany();
  await prisma.conversation.deleteMany();
  await prisma.review.deleteMany();
  await prisma.payment.deleteMany();
  await prisma.booking.deleteMany();
  await prisma.favorite.deleteMany();
  await prisma.propertyAmenity.deleteMany();
  await prisma.propertyRule.deleteMany();
  await prisma.propertyImage.deleteMany();
  await prisma.propertyVideo.deleteMany();
  await prisma.property.deleteMany();
  await prisma.ownerProfile.deleteMany();
  await prisma.user.deleteMany();

  const defaultPassword = await bcrypt.hash('password123', 10);
  const adminPassword = await bcrypt.hash('admin123', 10);

  // 1. Create Admin
  const adminUser = await prisma.user.create({
    data: {
      name: 'Priya Sharma (Admin)',
      email: 'admin@urbannest.com',
      password: adminPassword,
      phone: '+91 98765 00001',
      role: 'ADMIN',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
      gender: 'Female',
      occupation: 'Platform Administrator',
      preferredCity: 'Bengaluru',
      isVerified: true,
    },
  });

  // 2. Create 10 Owners
  const ownersData = [
    {
      name: 'Rajesh Mehra',
      email: 'rajesh.mehra@example.com',
      phone: '+91 98111 23456',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
      business: 'Mehra Stays & PGs',
      responseRate: 98,
      responseTime: 'Within 15 mins',
      city: 'Prayagraj',
    },
    {
      name: 'Sunita Venkatesh',
      email: 'sunita.v@example.com',
      phone: '+91 98222 34567',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&auto=format&fit=crop&q=80',
      business: 'Greenleaf Co-living',
      responseRate: 95,
      responseTime: 'Within 30 mins',
      city: 'Bengaluru',
    },
    {
      name: 'Vikramaditya Rao',
      email: 'vikram.rao@example.com',
      phone: '+91 98333 45678',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
      business: 'Urban Comforts Realty',
      responseRate: 99,
      responseTime: 'Within 10 mins',
      city: 'Hyderabad',
    },
    {
      name: 'Ananya Deshmukh',
      email: 'ananya.d@example.com',
      phone: '+91 98444 56789',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
      business: 'Deshmukh Residencies',
      responseRate: 92,
      responseTime: 'Within 1 hour',
      city: 'Pune',
    },
    {
      name: 'Harpreet Singh',
      email: 'harpreet.s@example.com',
      phone: '+91 98555 67890',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80',
      business: 'Golden Key Accommodations',
      responseRate: 96,
      responseTime: 'Within 20 mins',
      city: 'Delhi NCR',
    },
    {
      name: 'Deepak Agarwal',
      email: 'deepak.agarwal@example.com',
      phone: '+91 98666 78901',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
      business: 'Agarwal Hostels & Flats',
      responseRate: 94,
      responseTime: 'Within 45 mins',
      city: 'Prayagraj',
    },
    {
      name: 'Kavita Nair',
      email: 'kavita.nair@example.com',
      phone: '+91 98777 89012',
      avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=300&auto=format&fit=crop&q=80',
      business: 'Serene Haven Rooms',
      responseRate: 100,
      responseTime: 'Within 5 mins',
      city: 'Bengaluru',
    },
    {
      name: 'Manoj Kulkarni',
      email: 'manoj.k@example.com',
      phone: '+91 98888 90123',
      avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&auto=format&fit=crop&q=80',
      business: 'Kulkarni Estates',
      responseRate: 91,
      responseTime: 'Within 2 hours',
      city: 'Pune',
    },
    {
      name: 'Rohan Banerjee',
      email: 'rohan.b@example.com',
      phone: '+91 98999 01234',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80',
      business: 'MetroLiving PGs',
      responseRate: 97,
      responseTime: 'Within 15 mins',
      city: 'Mumbai',
    },
    {
      name: 'Suresh Narayanan',
      email: 'suresh.n@example.com',
      phone: '+91 98000 12345',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
      business: 'Southern Palms Stay',
      responseRate: 95,
      responseTime: 'Within 30 mins',
      city: 'Chennai',
    },
  ];

  const owners = [];
  for (const o of ownersData) {
    const user = await prisma.user.create({
      data: {
        name: o.name,
        email: o.email,
        password: defaultPassword,
        phone: o.phone,
        role: 'OWNER',
        avatar: o.avatar,
        gender: 'Male',
        preferredCity: o.city,
        isVerified: true,
        ownerProfile: {
          create: {
            businessName: o.business,
            idDocType: 'AADHAAR',
            idDocUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400',
            verificationStatus: 'VERIFIED',
            responseRate: o.responseRate,
            responseTime: o.responseTime,
          },
        },
      },
      include: { ownerProfile: true },
    });
    owners.push(user);
  }

  // 3. Create 10 Tenants / Users
  const tenantsData = [
    {
      name: 'Rahul Sharma',
      email: 'rahul.sharma@example.com',
      phone: '+91 97111 11111',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300&auto=format&fit=crop&q=80',
      gender: 'Male',
      occupation: 'Software Engineer',
      collegeOrCompany: 'Infosys Tech Park',
      preferredCity: 'Bengaluru',
      budget: 15000,
      preferredRoomType: 'Single',
    },
    {
      name: 'Sneha Patel',
      email: 'sneha.patel@example.com',
      phone: '+91 97222 22222',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
      gender: 'Female',
      occupation: 'Graduate Student',
      collegeOrCompany: 'University of Allahabad',
      preferredCity: 'Prayagraj',
      budget: 8000,
      preferredRoomType: 'PG',
    },
    {
      name: 'Aditya Verma',
      email: 'aditya.verma@example.com',
      phone: '+91 97333 33333',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
      gender: 'Male',
      occupation: 'Civil Services Aspirant',
      collegeOrCompany: 'Dhyeya IAS Academy',
      preferredCity: 'Prayagraj',
      budget: 7000,
      preferredRoomType: 'Single',
    },
    {
      name: 'Pooja Iyer',
      email: 'pooja.iyer@example.com',
      phone: '+91 97444 44444',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
      gender: 'Female',
      occupation: 'UX Designer',
      collegeOrCompany: 'Flipkart',
      preferredCity: 'Bengaluru',
      budget: 20000,
      preferredRoomType: '1BHK',
    },
    {
      name: 'Karan Mehra',
      email: 'karan.m@example.com',
      phone: '+91 97555 55555',
      avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=300&auto=format&fit=crop&q=80',
      gender: 'Male',
      occupation: 'Financial Analyst',
      collegeOrCompany: 'Deloitte Gurgaon',
      preferredCity: 'Delhi NCR',
      budget: 18000,
      preferredRoomType: 'Studio',
    },
    {
      name: 'Divya Reddy',
      email: 'divya.reddy@example.com',
      phone: '+91 97666 66666',
      avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=300&auto=format&fit=crop&q=80',
      gender: 'Female',
      occupation: 'AI Researcher',
      collegeOrCompany: 'Microsoft R&D',
      preferredCity: 'Hyderabad',
      budget: 22000,
      preferredRoomType: 'Single',
    },
    {
      name: 'Nikhil Joshi',
      email: 'nikhil.joshi@example.com',
      phone: '+91 97777 77777',
      avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&auto=format&fit=crop&q=80',
      gender: 'Male',
      occupation: 'Mechanical Engineer',
      collegeOrCompany: 'Tata Motors',
      preferredCity: 'Pune',
      budget: 11000,
      preferredRoomType: 'Shared',
    },
    {
      name: 'Aishwarya Sen',
      email: 'aishwarya.sen@example.com',
      phone: '+91 97888 88888',
      avatar: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=300&auto=format&fit=crop&q=80',
      gender: 'Female',
      occupation: 'Content Strategist',
      collegeOrCompany: 'Schbang Media',
      preferredCity: 'Mumbai',
      budget: 25000,
      preferredRoomType: 'Studio',
    },
    {
      name: 'Arjun Das',
      email: 'arjun.das@example.com',
      phone: '+91 97999 99999',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
      gender: 'Male',
      occupation: 'Cloud Consultant',
      collegeOrCompany: 'Cognizant OMR',
      preferredCity: 'Chennai',
      budget: 14000,
      preferredRoomType: 'Single',
    },
    {
      name: 'Tanvi Saxena',
      email: 'tanvi.saxena@example.com',
      phone: '+91 97000 00000',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
      gender: 'Female',
      occupation: 'Medical Intern',
      collegeOrCompany: 'MLN Medical College',
      preferredCity: 'Prayagraj',
      budget: 9500,
      preferredRoomType: 'PG',
    },
  ];

  const tenants = [];
  for (const t of tenantsData) {
    const user = await prisma.user.create({
      data: {
        ...t,
        password: defaultPassword,
        role: 'USER',
        isVerified: true,
      },
    });
    tenants.push(user);
  }

  // 4. Create 20+ Realistic Properties across India
  const propertiesData = [
    // Prayagraj Properties
    {
      title: 'Modern Single Room with Balcony in Civil Lines',
      slug: 'modern-single-room-balcony-civil-lines-prayagraj',
      description: 'Bright and airy private room located in the prestigious Civil Lines neighborhood. Features high-speed Wi-Fi, split air conditioner, attached contemporary bathroom, and dedicated study desk. Perfect for working professionals and university scholars.',
      propertyType: 'Independent House',
      roomType: 'Single',
      furnishing: 'Fully furnished',
      floor: 2,
      totalFloors: 3,
      roomSizeSqft: 220,
      bathrooms: 1,
      balconies: 1,
      kitchenType: 'Shared',
      parkingType: 'Two Wheeler',
      rentMonthly: 8500,
      deposit: 8500,
      maintenanceCharges: 500,
      electricityIncluded: false,
      waterIncluded: true,
      foodIncluded: false,
      genderPreference: 'Any',
      tenantPreference: 'Working Professionals',
      country: 'India',
      state: 'Uttar Pradesh',
      city: 'Prayagraj',
      area: 'Civil Lines',
      address: '24/B, Sardar Patel Marg, Near High Court',
      landmark: 'Near El Chico Restaurant',
      latitude: 25.4526,
      longitude: 81.8349,
      distanceToHub: '600m to Prayagraj Junction Railway Station',
      status: 'PUBLISHED',
      isVerified: true,
      featured: true,
      noBrokerage: true,
      ownerIdx: 0,
      images: [
        'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=1000&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1000&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1000&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=1000&auto=format&fit=crop&q=80',
      ],
      amenities: [
        { name: 'High-Speed Wi-Fi', category: 'Essentials', iconKey: 'wifi' },
        { name: 'Air Conditioning', category: 'Comfort', iconKey: 'ac' },
        { name: 'Attached Bathroom', category: 'Features', iconKey: 'bath' },
        { name: 'Power Backup', category: 'Essentials', iconKey: 'power' },
        { name: 'CCTV Security', category: 'Safety', iconKey: 'cctv' },
        { name: 'Geyser', category: 'Comfort', iconKey: 'geyser' },
      ],
      rules: [
        { ruleText: 'Quiet hours after 10:30 PM', ruleType: 'ALLOWED' },
        { ruleText: 'No smoking indoors', ruleType: 'NOT_ALLOWED' },
        { ruleText: 'Daytime visitors permitted', ruleType: 'ALLOWED' },
      ],
    },
    {
      title: 'Premium Student PG with 3-Time Meals in Katra',
      slug: 'student-pg-meals-katra-prayagraj',
      description: 'Ideal student accommodation situated 500 meters from Allahabad University Arts Campus. Includes 3 nutritious home-style meals daily, RO drinking water, 24x7 power backup, study library room, and daily housekeeping.',
      propertyType: 'PG',
      roomType: 'Double',
      furnishing: 'Fully furnished',
      floor: 1,
      totalFloors: 4,
      roomSizeSqft: 280,
      bathrooms: 1,
      balconies: 0,
      kitchenType: 'None',
      parkingType: 'Two Wheeler',
      rentMonthly: 6200,
      deposit: 6200,
      maintenanceCharges: 0,
      electricityIncluded: true,
      waterIncluded: true,
      foodIncluded: true,
      genderPreference: 'Male',
      tenantPreference: 'Students',
      country: 'India',
      state: 'Uttar Pradesh',
      city: 'Prayagraj',
      area: 'Katra',
      address: '112/4, University Road, Katra Bazaar',
      landmark: 'Near Anand Bhawan & AU Arts Faculty',
      latitude: 25.4601,
      longitude: 81.8592,
      distanceToHub: '400m to Allahabad University',
      status: 'PUBLISHED',
      isVerified: true,
      featured: false,
      noBrokerage: true,
      ownerIdx: 5,
      images: [
        'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1000&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1000&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=1000&auto=format&fit=crop&q=80',
      ],
      amenities: [
        { name: '3 Meals Included', category: 'Services', iconKey: 'food' },
        { name: 'High-Speed Wi-Fi', category: 'Essentials', iconKey: 'wifi' },
        { name: 'RO Water Purifier', category: 'Essentials', iconKey: 'water' },
        { name: 'Housekeeping', category: 'Services', iconKey: 'cleaning' },
        { name: 'Power Backup', category: 'Essentials', iconKey: 'power' },
      ],
      rules: [
        { ruleText: 'Curfew at 10:00 PM', ruleType: 'CONDITIONAL' },
        { ruleText: 'Non-veg cooking restricted', ruleType: 'NOT_ALLOWED' },
      ],
    },
    {
      title: 'Spacious 1BHK Studio Apartment in Georgetown',
      slug: 'spacious-1bhk-studio-apartment-georgetown-prayagraj',
      description: 'Elegant independent 1BHK floor with modular kitchen, private balcony overlooking green gardens, king bed, and dedicated car parking. Quiet residential enclave close to Tagore Town and Civil Lines.',
      propertyType: 'Apartment',
      roomType: '1BHK',
      furnishing: 'Fully furnished',
      floor: 1,
      totalFloors: 2,
      roomSizeSqft: 520,
      bathrooms: 1,
      balconies: 2,
      kitchenType: 'Private',
      parkingType: 'Both',
      rentMonthly: 13500,
      deposit: 20000,
      maintenanceCharges: 800,
      electricityIncluded: false,
      waterIncluded: true,
      foodIncluded: false,
      genderPreference: 'Any',
      tenantPreference: 'Family',
      country: 'India',
      state: 'Uttar Pradesh',
      city: 'Prayagraj',
      area: 'Georgetown',
      address: '77/12, Lowther Road, Georgetown',
      landmark: 'Behind Medical College Chauraha',
      latitude: 25.4412,
      longitude: 81.8541,
      distanceToHub: '1.2 km to Medical College & Sangam Marg',
      status: 'PUBLISHED',
      isVerified: true,
      featured: true,
      noBrokerage: true,
      ownerIdx: 0,
      images: [
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1000&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1000&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1000&auto=format&fit=crop&q=80',
      ],
      amenities: [
        { name: 'Private Kitchen', category: 'Features', iconKey: 'kitchen' },
        { name: 'Covered Car Parking', category: 'Features', iconKey: 'parking' },
        { name: 'Air Conditioning', category: 'Comfort', iconKey: 'ac' },
        { name: 'Washing Machine', category: 'Essentials', iconKey: 'washer' },
        { name: 'Refrigerator', category: 'Features', iconKey: 'fridge' },
      ],
      rules: [
        { ruleText: 'Small pets allowed on request', ruleType: 'CONDITIONAL' },
      ],
    },
    {
      title: 'Cozy Budget Single Room near Tagore Town',
      slug: 'cozy-budget-single-room-tagore-town-prayagraj',
      description: 'Affordable, clean single room with peaceful ambiance. High ventilation, study desk, single bed with orthopedic mattress, wardrobe, and access to clean shared washroom and terrace.',
      propertyType: 'Independent House',
      roomType: 'Single',
      furnishing: 'Semi furnished',
      floor: 2,
      totalFloors: 3,
      roomSizeSqft: 160,
      bathrooms: 1,
      balconies: 1,
      kitchenType: 'Shared',
      parkingType: 'Two Wheeler',
      rentMonthly: 4800,
      deposit: 4800,
      maintenanceCharges: 200,
      electricityIncluded: false,
      waterIncluded: true,
      foodIncluded: false,
      genderPreference: 'Any',
      tenantPreference: 'Students',
      country: 'India',
      state: 'Uttar Pradesh',
      city: 'Prayagraj',
      area: 'Tagore Town',
      address: '42, Dr. Katju Road, Tagore Town',
      landmark: 'Near Colonelganj Inter College',
      latitude: 25.4498,
      longitude: 81.8601,
      distanceToHub: '800m to Tagore Town Market',
      status: 'PUBLISHED',
      isVerified: true,
      featured: false,
      noBrokerage: true,
      ownerIdx: 5,
      images: [
        'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=1000&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=1000&auto=format&fit=crop&q=80',
      ],
      amenities: [
        { name: 'Wi-Fi 100 Mbps', category: 'Essentials', iconKey: 'wifi' },
        { name: 'RO Water', category: 'Essentials', iconKey: 'water' },
        { name: 'Power Backup', category: 'Essentials', iconKey: 'power' },
      ],
      rules: [
        { ruleText: 'No loud music after 11 PM', ruleType: 'NOT_ALLOWED' },
      ],
    },

    // Bengaluru Properties
    {
      title: 'Chic Luxury Studio in Koramangala 4th Block',
      slug: 'chic-luxury-studio-koramangala-bengaluru',
      description: 'Sophisticated designer studio suite featuring ergonomic workstation, smart TV, queen bed, designer kitchenette, gym access, and rooftop lounge. Situated in Bangalore’s prime culinary and startup district.',
      propertyType: 'Apartment',
      roomType: 'Studio',
      furnishing: 'Fully furnished',
      floor: 3,
      totalFloors: 5,
      roomSizeSqft: 380,
      bathrooms: 1,
      balconies: 1,
      kitchenType: 'Private',
      parkingType: 'Both',
      rentMonthly: 24000,
      deposit: 40000,
      maintenanceCharges: 1500,
      electricityIncluded: false,
      waterIncluded: true,
      foodIncluded: false,
      genderPreference: 'Any',
      tenantPreference: 'Working Professionals',
      country: 'India',
      state: 'Karnataka',
      city: 'Bengaluru',
      area: 'Koramangala',
      address: '142, 80 Feet Road, 4th Block Koramangala',
      landmark: 'Opposite Sony World Signal',
      latitude: 12.9345,
      longitude: 77.6266,
      distanceToHub: '400m to 100 Feet Road Food Street',
      status: 'PUBLISHED',
      isVerified: true,
      featured: true,
      noBrokerage: true,
      ownerIdx: 1,
      images: [
        'https://images.unsplash.com/photo-1502005229762-ee1b2da9730f?w=1000&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1000&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1000&auto=format&fit=crop&q=80',
      ],
      amenities: [
        { name: 'Ultra High-Speed Wi-Fi', category: 'Essentials', iconKey: 'wifi' },
        { name: 'Split Air Conditioner', category: 'Comfort', iconKey: 'ac' },
        { name: 'Smart LED TV', category: 'Entertainment', iconKey: 'tv' },
        { name: 'Lift with Power Backup', category: 'Comfort', iconKey: 'lift' },
        { name: 'Washing Machine', category: 'Essentials', iconKey: 'washer' },
      ],
      rules: [
        { ruleText: 'Pets allowed', ruleType: 'ALLOWED' },
        { ruleText: 'Visitors welcome', ruleType: 'ALLOWED' },
      ],
    },
    {
      title: 'Premium Co-living Private Room near HSR BDA Complex',
      slug: 'coliving-private-room-hsr-layout-bengaluru',
      description: 'Hassle-free managed co-living private room in Sector 2 HSR Layout. Includes bi-weekly housekeeping, community events, gaming console zone, high speed fiber optic internet, and app-based maintenance.',
      propertyType: 'Co-living',
      roomType: 'Single',
      furnishing: 'Fully furnished',
      floor: 2,
      totalFloors: 4,
      roomSizeSqft: 240,
      bathrooms: 1,
      balconies: 1,
      kitchenType: 'Shared',
      parkingType: 'Two Wheeler',
      rentMonthly: 16500,
      deposit: 25000,
      maintenanceCharges: 0,
      electricityIncluded: false,
      waterIncluded: true,
      foodIncluded: false,
      genderPreference: 'Any',
      tenantPreference: 'Working Professionals',
      country: 'India',
      state: 'Karnataka',
      city: 'Bengaluru',
      area: 'HSR Layout',
      address: 'Sector 2, 27th Main Road, HSR Layout',
      landmark: 'Near NIFT Campus & BDA Complex',
      latitude: 12.9116,
      longitude: 77.6474,
      distanceToHub: '1.5 km to Silk Board Junction',
      status: 'PUBLISHED',
      isVerified: true,
      featured: true,
      noBrokerage: true,
      ownerIdx: 6,
      images: [
        'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=1000&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1000&auto=format&fit=crop&q=80',
      ],
      amenities: [
        { name: 'High-Speed Wi-Fi', category: 'Essentials', iconKey: 'wifi' },
        { name: 'Air Conditioning', category: 'Comfort', iconKey: 'ac' },
        { name: 'Housekeeping Included', category: 'Services', iconKey: 'cleaning' },
        { name: 'CCTV Security', category: 'Safety', iconKey: 'cctv' },
      ],
      rules: [
        { ruleText: 'No smoking inside bedrooms', ruleType: 'NOT_ALLOWED' },
      ],
    },
    {
      title: 'Modern 2BHK Shared Flat Room in Indiranagar',
      slug: 'shared-flat-room-indiranagar-bengaluru',
      description: 'Private master bedroom with ensuite bath in a sprawling 2BHK apartment in quiet Defence Colony, Indiranagar. Walking distance to 100 Ft Road metro station, breweries, and organic supermarkets.',
      propertyType: 'Flat',
      roomType: 'Single',
      furnishing: 'Fully furnished',
      floor: 2,
      totalFloors: 3,
      roomSizeSqft: 260,
      bathrooms: 1,
      balconies: 1,
      kitchenType: 'Shared',
      parkingType: 'Both',
      rentMonthly: 19500,
      deposit: 35000,
      maintenanceCharges: 1200,
      electricityIncluded: false,
      waterIncluded: true,
      foodIncluded: false,
      genderPreference: 'Any',
      tenantPreference: 'Working Professionals',
      country: 'India',
      state: 'Karnataka',
      city: 'Bengaluru',
      area: 'Indiranagar',
      address: '68, Defence Colony, 2nd Main, Indiranagar',
      landmark: 'Near Indiranagar Metro Station',
      latitude: 12.9784,
      longitude: 77.6408,
      distanceToHub: '500m to Indiranagar Metro Station',
      status: 'PUBLISHED',
      isVerified: true,
      featured: false,
      noBrokerage: true,
      ownerIdx: 1,
      images: [
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1000&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1000&auto=format&fit=crop&q=80',
      ],
      amenities: [
        { name: 'High-Speed Wi-Fi', category: 'Essentials', iconKey: 'wifi' },
        { name: 'Attached Bath & Geyser', category: 'Comfort', iconKey: 'bath' },
        { name: 'Washing Machine', category: 'Essentials', iconKey: 'washer' },
        { name: 'Car Parking', category: 'Features', iconKey: 'parking' },
      ],
      rules: [
        { ruleText: 'Pet friendly', ruleType: 'ALLOWED' },
      ],
    },
    {
      title: 'Budget Single PG Room in Electronic City Phase 1',
      slug: 'budget-single-pg-electronic-city-bengaluru',
      description: 'Ideal accommodation for tech employees working in Infosys, Wipro, and HP campus. Clean furnished room with breakfast and dinner, fast WiFi, and power backup.',
      propertyType: 'PG',
      roomType: 'Single',
      furnishing: 'Fully furnished',
      floor: 1,
      totalFloors: 4,
      roomSizeSqft: 180,
      bathrooms: 1,
      balconies: 0,
      kitchenType: 'None',
      parkingType: 'Two Wheeler',
      rentMonthly: 8900,
      deposit: 10000,
      maintenanceCharges: 0,
      electricityIncluded: true,
      waterIncluded: true,
      foodIncluded: true,
      genderPreference: 'Any',
      tenantPreference: 'Working Professionals',
      country: 'India',
      state: 'Karnataka',
      city: 'Bengaluru',
      area: 'Electronic City',
      address: 'Plot 34, Doddathoguru, Electronic City Phase 1',
      landmark: 'Near Infosys Gate 6',
      latitude: 12.8452,
      longitude: 77.6602,
      distanceToHub: '600m to Infosys Campus',
      status: 'PUBLISHED',
      isVerified: true,
      featured: false,
      noBrokerage: true,
      ownerIdx: 6,
      images: [
        'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1000&auto=format&fit=crop&q=80',
      ],
      amenities: [
        { name: 'Meals Included', category: 'Services', iconKey: 'food' },
        { name: 'Wi-Fi', category: 'Essentials', iconKey: 'wifi' },
        { name: 'Power Backup', category: 'Essentials', iconKey: 'power' },
      ],
      rules: [],
    },

    // Pune Properties
    {
      title: 'Modern Single Studio in Viman Nagar near Symbiosis',
      slug: 'single-studio-viman-nagar-pune',
      description: 'Tastefully furnished studio room 800m from Symbiosis International School & College. Packed with comfortable mattress, study chair, kitchenette, high-speed optic fiber, and biometric security entrance.',
      propertyType: 'Apartment',
      roomType: 'Studio',
      furnishing: 'Fully furnished',
      floor: 3,
      totalFloors: 6,
      roomSizeSqft: 320,
      bathrooms: 1,
      balconies: 1,
      kitchenType: 'Private',
      parkingType: 'Two Wheeler',
      rentMonthly: 15000,
      deposit: 25000,
      maintenanceCharges: 1000,
      electricityIncluded: false,
      waterIncluded: true,
      foodIncluded: false,
      genderPreference: 'Any',
      tenantPreference: 'Students',
      country: 'India',
      state: 'Maharashtra',
      city: 'Pune',
      area: 'Viman Nagar',
      address: 'B-402, Clover Park, Viman Nagar',
      landmark: 'Near Phoenix Marketcity',
      latitude: 18.5679,
      longitude: 73.9143,
      distanceToHub: '700m to Phoenix Marketcity Mall',
      status: 'PUBLISHED',
      isVerified: true,
      featured: true,
      noBrokerage: true,
      ownerIdx: 3,
      images: [
        'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1000&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=1000&auto=format&fit=crop&q=80',
      ],
      amenities: [
        { name: 'Optic Fiber Wi-Fi', category: 'Essentials', iconKey: 'wifi' },
        { name: 'Air Conditioning', category: 'Comfort', iconKey: 'ac' },
        { name: 'Biometric Access', category: 'Safety', iconKey: 'security' },
        { name: 'Lift Access', category: 'Comfort', iconKey: 'lift' },
      ],
      rules: [
        { ruleText: 'No smoking indoors', ruleType: 'NOT_ALLOWED' },
      ],
    },
    {
      title: 'Comfortable Shared Room in Hinjewadi Phase 1',
      slug: 'shared-room-hinjewadi-phase-1-pune',
      description: 'Twin sharing room in a gated luxury society. Gym, swimming pool, badminton court, clubhouse access included in society maintenance. Free shuttle service to Rajiv Gandhi Infotech Park.',
      propertyType: 'Flat',
      roomType: 'Shared',
      furnishing: 'Fully furnished',
      floor: 7,
      totalFloors: 14,
      roomSizeSqft: 260,
      bathrooms: 1,
      balconies: 1,
      kitchenType: 'Shared',
      parkingType: 'Both',
      rentMonthly: 7800,
      deposit: 12000,
      maintenanceCharges: 600,
      electricityIncluded: false,
      waterIncluded: true,
      foodIncluded: false,
      genderPreference: 'Male',
      tenantPreference: 'Working Professionals',
      country: 'India',
      state: 'Maharashtra',
      city: 'Pune',
      area: 'Hinjewadi',
      address: 'Tower 3, Megapolis Smart Homes, Hinjewadi Phase 3',
      landmark: 'Near Cognizant & Tech Mahindra',
      latitude: 18.5912,
      longitude: 73.7123,
      distanceToHub: '1 km to Hinjewadi Phase 1 Circle',
      status: 'PUBLISHED',
      isVerified: true,
      featured: false,
      noBrokerage: true,
      ownerIdx: 7,
      images: [
        'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=1000&auto=format&fit=crop&q=80',
      ],
      amenities: [
        { name: 'Swimming Pool & Gym', category: 'Features', iconKey: 'gym' },
        { name: 'Wi-Fi', category: 'Essentials', iconKey: 'wifi' },
        { name: 'Power Backup', category: 'Essentials', iconKey: 'power' },
      ],
      rules: [],
    },
    {
      title: 'Independent 1BHK Flat in Baner',
      slug: 'independent-1bhk-flat-baner-pune',
      description: 'Serene standalone 1BHK with marble floors, modular granite kitchen, master bedroom with balcony, peaceful garden view. Minutes from Mumbai-Pune Expressway bypass.',
      propertyType: 'Apartment',
      roomType: '1BHK',
      furnishing: 'Semi furnished',
      floor: 2,
      totalFloors: 4,
      roomSizeSqft: 580,
      bathrooms: 1,
      balconies: 2,
      kitchenType: 'Private',
      parkingType: 'Four Wheeler',
      rentMonthly: 17000,
      deposit: 30000,
      maintenanceCharges: 1000,
      electricityIncluded: false,
      waterIncluded: true,
      foodIncluded: false,
      genderPreference: 'Any',
      tenantPreference: 'Any',
      country: 'India',
      state: 'Maharashtra',
      city: 'Pune',
      area: 'Baner',
      address: 'Pan Card Club Road, Baner',
      landmark: 'Near Balewadi High Street',
      latitude: 18.5590,
      longitude: 73.7868,
      distanceToHub: '1.2 km to Balewadi High Street',
      status: 'PUBLISHED',
      isVerified: true,
      featured: true,
      noBrokerage: true,
      ownerIdx: 7,
      images: [
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1000&auto=format&fit=crop&q=80',
      ],
      amenities: [
        { name: 'Covered Parking', category: 'Features', iconKey: 'parking' },
        { name: 'Power Backup', category: 'Essentials', iconKey: 'power' },
      ],
      rules: [],
    },

    // Delhi NCR Properties
    {
      title: 'Bohemian Single Room in Hauz Khas Village',
      slug: 'bohemian-single-room-hauz-khas-delhi',
      description: 'Boutique single room overlooking the historic Hauz Khas deer park & lake. High wooden ceilings, artistic interior, air purifier, microwave, mini-fridge, and ultra-fast WiFi for remote work.',
      propertyType: 'Independent House',
      roomType: 'Single',
      furnishing: 'Fully furnished',
      floor: 2,
      totalFloors: 3,
      roomSizeSqft: 250,
      bathrooms: 1,
      balconies: 1,
      kitchenType: 'Shared',
      parkingType: 'None',
      rentMonthly: 21000,
      deposit: 30000,
      maintenanceCharges: 1000,
      electricityIncluded: false,
      waterIncluded: true,
      foodIncluded: false,
      genderPreference: 'Any',
      tenantPreference: 'Working Professionals',
      country: 'India',
      state: 'Delhi',
      city: 'Delhi NCR',
      area: 'Hauz Khas',
      address: '12/A, Hauz Khas Village',
      landmark: 'Adjacent to Deer Park Gate',
      latitude: 28.5535,
      longitude: 77.1947,
      distanceToHub: '800m to IIT Delhi & Green Park Metro',
      status: 'PUBLISHED',
      isVerified: true,
      featured: true,
      noBrokerage: true,
      ownerIdx: 4,
      images: [
        'https://images.unsplash.com/photo-1502005229762-ee1b2da9730f?w=1000&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1000&auto=format&fit=crop&q=80',
      ],
      amenities: [
        { name: 'Wi-Fi 300 Mbps', category: 'Essentials', iconKey: 'wifi' },
        { name: 'Air Conditioning', category: 'Comfort', iconKey: 'ac' },
        { name: 'Attached Bathroom', category: 'Features', iconKey: 'bath' },
      ],
      rules: [
        { ruleText: 'Pet friendly', ruleType: 'ALLOWED' },
      ],
    },
    {
      title: 'Executive Room near Cyber City Phase 2 Gurgaon',
      slug: 'executive-room-cyber-city-gurgaon',
      description: 'Executive corporate room 5 minutes from Cyber Hub. Features double bed, central AC, housekeeping, laundry service, high-speed desk setup, and 100% DG power backup.',
      propertyType: 'Co-living',
      roomType: 'Single',
      furnishing: 'Fully furnished',
      floor: 3,
      totalFloors: 4,
      roomSizeSqft: 280,
      bathrooms: 1,
      balconies: 1,
      kitchenType: 'Shared',
      parkingType: 'Both',
      rentMonthly: 19000,
      deposit: 25000,
      maintenanceCharges: 0,
      electricityIncluded: false,
      waterIncluded: true,
      foodIncluded: false,
      genderPreference: 'Any',
      tenantPreference: 'Working Professionals',
      country: 'India',
      state: 'Haryana',
      city: 'Delhi NCR',
      area: 'Gurgaon',
      address: 'DLF Phase 2, Near Sikanderpur Metro',
      landmark: 'Behind Cyber Hub Rapid Metro',
      latitude: 28.4899,
      longitude: 77.0911,
      distanceToHub: '600m to Cyber Hub',
      status: 'PUBLISHED',
      isVerified: true,
      featured: true,
      noBrokerage: true,
      ownerIdx: 4,
      images: [
        'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1000&auto=format&fit=crop&q=80',
      ],
      amenities: [
        { name: 'Air Conditioning', category: 'Comfort', iconKey: 'ac' },
        { name: 'Wi-Fi', category: 'Essentials', iconKey: 'wifi' },
        { name: '100% Power Backup', category: 'Essentials', iconKey: 'power' },
      ],
      rules: [],
    },
    {
      title: 'Student Girls PG in Mukherjee Nagar North Delhi',
      slug: 'girls-pg-mukherjee-nagar-delhi',
      description: 'Safe and secure girls PG with 24x7 female warden, biometric entry, three delicious home-style meals, AC, geyser, study library, and daily sanitized cleaning. 5 mins walk to coaching institutes.',
      propertyType: 'PG',
      roomType: 'Double',
      furnishing: 'Fully furnished',
      floor: 1,
      totalFloors: 4,
      roomSizeSqft: 220,
      bathrooms: 1,
      balconies: 0,
      kitchenType: 'None',
      parkingType: 'Two Wheeler',
      rentMonthly: 8500,
      deposit: 8500,
      maintenanceCharges: 0,
      electricityIncluded: true,
      waterIncluded: true,
      foodIncluded: true,
      genderPreference: 'Female',
      tenantPreference: 'Students',
      country: 'India',
      state: 'Delhi',
      city: 'Delhi NCR',
      area: 'Mukherjee Nagar',
      address: 'B-16, Commercial Complex, Mukherjee Nagar',
      landmark: 'Near Batra Cinema & Drishti IAS',
      latitude: 28.7077,
      longitude: 77.2081,
      distanceToHub: '300m to GTB Nagar Metro Station',
      status: 'PUBLISHED',
      isVerified: true,
      featured: false,
      noBrokerage: true,
      ownerIdx: 4,
      images: [
        'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1000&auto=format&fit=crop&q=80',
      ],
      amenities: [
        { name: 'Food Included (3 Times)', category: 'Services', iconKey: 'food' },
        { name: 'Biometric & CCTV', category: 'Safety', iconKey: 'cctv' },
        { name: 'Wi-Fi', category: 'Essentials', iconKey: 'wifi' },
      ],
      rules: [
        { ruleText: 'Girls only accommodation', ruleType: 'ALLOWED' },
        { ruleText: 'Curfew at 9:30 PM', ruleType: 'CONDITIONAL' },
      ],
    },

    // Hyderabad Properties
    {
      title: 'Luxury Coliving Studio in Hitec City Gachibowli',
      slug: 'coliving-studio-hitec-city-hyderabad',
      description: 'Ultra-modern private studio in Hyderabad’s IT Corridor. Features automated smart lighting, workstation, king bed, kitchenette, rooftop infinity pool, and gym membership.',
      propertyType: 'Co-living',
      roomType: 'Studio',
      furnishing: 'Fully furnished',
      floor: 5,
      totalFloors: 9,
      roomSizeSqft: 360,
      bathrooms: 1,
      balconies: 1,
      kitchenType: 'Private',
      parkingType: 'Both',
      rentMonthly: 23000,
      deposit: 35000,
      maintenanceCharges: 1500,
      electricityIncluded: false,
      waterIncluded: true,
      foodIncluded: false,
      genderPreference: 'Any',
      tenantPreference: 'Working Professionals',
      country: 'India',
      state: 'Telangana',
      city: 'Hyderabad',
      area: 'Hitec City',
      address: 'Mindspace Road, Madhapur, Hitec City',
      landmark: 'Opposite Inorbit Mall',
      latitude: 17.4375,
      longitude: 78.3814,
      distanceToHub: '400m to Raidurg Metro Station',
      status: 'PUBLISHED',
      isVerified: true,
      featured: true,
      noBrokerage: true,
      ownerIdx: 2,
      images: [
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1000&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1000&auto=format&fit=crop&q=80',
      ],
      amenities: [
        { name: 'Rooftop Pool & Gym', category: 'Features', iconKey: 'gym' },
        { name: 'Split AC', category: 'Comfort', iconKey: 'ac' },
        { name: 'Ultra High-Speed Wi-Fi', category: 'Essentials', iconKey: 'wifi' },
      ],
      rules: [],
    },
    {
      title: 'Budget Single Room with Food in Gachibowli',
      slug: 'budget-single-room-food-gachibowli-hyderabad',
      description: 'Affordable single occupancy PG room close to Amazon, Google, and Microsoft campuses. High-speed broadband, South/North Indian food, and housekeeping.',
      propertyType: 'PG',
      roomType: 'Single',
      furnishing: 'Fully furnished',
      floor: 2,
      totalFloors: 5,
      roomSizeSqft: 200,
      bathrooms: 1,
      balconies: 0,
      kitchenType: 'None',
      parkingType: 'Two Wheeler',
      rentMonthly: 9800,
      deposit: 10000,
      maintenanceCharges: 0,
      electricityIncluded: true,
      waterIncluded: true,
      foodIncluded: true,
      genderPreference: 'Any',
      tenantPreference: 'Working Professionals',
      country: 'India',
      state: 'Telangana',
      city: 'Hyderabad',
      area: 'Gachibowli',
      address: 'Telecom Nagar, Gachibowli',
      landmark: 'Near DLF Cybercity',
      latitude: 17.4401,
      longitude: 78.3489,
      distanceToHub: '1 km to DLF Gate',
      status: 'PUBLISHED',
      isVerified: true,
      featured: false,
      noBrokerage: true,
      ownerIdx: 2,
      images: [
        'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1000&auto=format&fit=crop&q=80',
      ],
      amenities: [
        { name: 'Food Included', category: 'Services', iconKey: 'food' },
        { name: 'Wi-Fi', category: 'Essentials', iconKey: 'wifi' },
        { name: 'Power Backup', category: 'Essentials', iconKey: 'power' },
      ],
      rules: [],
    },

    // Mumbai Properties
    {
      title: 'Bright Studio Apartment in Andheri West',
      slug: 'bright-studio-apartment-andheri-west-mumbai',
      description: 'Charming studio flat in prime Lokhandwala Complex. Close to Versova beach, metro station, cafes, and media production houses.',
      propertyType: 'Apartment',
      roomType: 'Studio',
      furnishing: 'Fully furnished',
      floor: 4,
      totalFloors: 8,
      roomSizeSqft: 340,
      bathrooms: 1,
      balconies: 1,
      kitchenType: 'Private',
      parkingType: 'Two Wheeler',
      rentMonthly: 28000,
      deposit: 50000,
      maintenanceCharges: 1500,
      electricityIncluded: false,
      waterIncluded: true,
      foodIncluded: false,
      genderPreference: 'Any',
      tenantPreference: 'Any',
      country: 'India',
      state: 'Maharashtra',
      city: 'Mumbai',
      area: 'Andheri West',
      address: 'Lokhandwala Complex, Main Market, Andheri West',
      landmark: 'Near Infinity Mall',
      latitude: 19.1363,
      longitude: 72.8277,
      distanceToHub: '900m to DN Nagar Metro Station',
      status: 'PUBLISHED',
      isVerified: true,
      featured: true,
      noBrokerage: true,
      ownerIdx: 8,
      images: [
        'https://images.unsplash.com/photo-1502005229762-ee1b2da9730f?w=1000&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1000&auto=format&fit=crop&q=80',
      ],
      amenities: [
        { name: 'Air Conditioning', category: 'Comfort', iconKey: 'ac' },
        { name: 'Wi-Fi', category: 'Essentials', iconKey: 'wifi' },
        { name: 'Washing Machine', category: 'Essentials', iconKey: 'washer' },
      ],
      rules: [],
    },
    {
      title: 'Shared Flat Room near Powai Lake IIT Bombay',
      slug: 'shared-flat-room-powai-mumbai',
      description: 'Private room in a 3BHK high-rise overlooking Powai Lake. 5 minutes from IIT Bombay Main Gate. Society offers jogging track, gym, and 24x7 security.',
      propertyType: 'Flat',
      roomType: 'Single',
      furnishing: 'Fully furnished',
      floor: 12,
      totalFloors: 22,
      roomSizeSqft: 240,
      bathrooms: 1,
      balconies: 1,
      kitchenType: 'Shared',
      parkingType: 'Both',
      rentMonthly: 22000,
      deposit: 35000,
      maintenanceCharges: 1000,
      electricityIncluded: false,
      waterIncluded: true,
      foodIncluded: false,
      genderPreference: 'Any',
      tenantPreference: 'Students',
      country: 'India',
      state: 'Maharashtra',
      city: 'Mumbai',
      area: 'Powai',
      address: 'Hiranandani Gardens, Powai',
      landmark: 'Near IIT Bombay Main Gate',
      latitude: 19.1176,
      longitude: 72.9060,
      distanceToHub: '400m to IIT Bombay',
      status: 'PUBLISHED',
      isVerified: true,
      featured: false,
      noBrokerage: true,
      ownerIdx: 8,
      images: [
        'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=1000&auto=format&fit=crop&q=80',
      ],
      amenities: [
        { name: 'Wi-Fi', category: 'Essentials', iconKey: 'wifi' },
        { name: 'Gym Access', category: 'Features', iconKey: 'gym' },
        { name: 'Security 24x7', category: 'Safety', iconKey: 'cctv' },
      ],
      rules: [],
    },

    // Chennai Properties
    {
      title: 'Spacious Single Room in OMR Thoraipakkam',
      slug: 'spacious-single-room-omr-chennai',
      description: 'Furnished air-conditioned single room in OMR IT corridor. 5 minutes from Cognizant, TCS, and BSR Mall. Includes high-speed broadband, inverter backup, and reserved parking.',
      propertyType: 'Independent House',
      roomType: 'Single',
      furnishing: 'Fully furnished',
      floor: 1,
      totalFloors: 3,
      roomSizeSqft: 240,
      bathrooms: 1,
      balconies: 1,
      kitchenType: 'Shared',
      parkingType: 'Both',
      rentMonthly: 10500,
      deposit: 15000,
      maintenanceCharges: 500,
      electricityIncluded: false,
      waterIncluded: true,
      foodIncluded: false,
      genderPreference: 'Any',
      tenantPreference: 'Working Professionals',
      country: 'India',
      state: 'Tamil Nadu',
      city: 'Chennai',
      area: 'OMR Thoraipakkam',
      address: 'Rajiv Gandhi Salai, Thoraipakkam, OMR',
      landmark: 'Near AKDR Golf Village',
      latitude: 12.9416,
      longitude: 80.2362,
      distanceToHub: '800m to Cognizant OMR Campus',
      status: 'PUBLISHED',
      isVerified: true,
      featured: false,
      noBrokerage: true,
      ownerIdx: 9,
      images: [
        'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1000&auto=format&fit=crop&q=80',
      ],
      amenities: [
        { name: 'Air Conditioning', category: 'Comfort', iconKey: 'ac' },
        { name: 'Wi-Fi', category: 'Essentials', iconKey: 'wifi' },
        { name: 'Power Backup', category: 'Essentials', iconKey: 'power' },
      ],
      rules: [],
    },
    {
      title: 'Serene Studio Room in Adyar near IIT Madras',
      slug: 'studio-room-adyar-chennai',
      description: 'Peaceful studio in leafy Adyar, walking distance from IIT Madras gate and Malar Hospital. Includes kitchen counter, refrigerator, split AC, and wardrobe.',
      propertyType: 'Apartment',
      roomType: 'Studio',
      furnishing: 'Fully furnished',
      floor: 2,
      totalFloors: 4,
      roomSizeSqft: 310,
      bathrooms: 1,
      balconies: 1,
      kitchenType: 'Private',
      parkingType: 'Two Wheeler',
      rentMonthly: 16000,
      deposit: 25000,
      maintenanceCharges: 800,
      electricityIncluded: false,
      waterIncluded: true,
      foodIncluded: false,
      genderPreference: 'Any',
      tenantPreference: 'Any',
      country: 'India',
      state: 'Tamil Nadu',
      city: 'Chennai',
      area: 'Adyar',
      address: 'Gandhi Nagar 2nd Main Road, Adyar',
      landmark: 'Near Fortis Malar Hospital',
      latitude: 13.0012,
      longitude: 80.2565,
      distanceToHub: '1 km to IIT Madras Gate',
      status: 'PUBLISHED',
      isVerified: true,
      featured: true,
      noBrokerage: true,
      ownerIdx: 9,
      images: [
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1000&auto=format&fit=crop&q=80',
      ],
      amenities: [
        { name: 'Air Conditioning', category: 'Comfort', iconKey: 'ac' },
        { name: 'Wi-Fi', category: 'Essentials', iconKey: 'wifi' },
        { name: 'Refrigerator', category: 'Features', iconKey: 'fridge' },
      ],
      rules: [],
    },
  ];

  const createdProperties = [];
  for (const p of propertiesData) {
    const owner = owners[p.ownerIdx % owners.length];
    const property = await prisma.property.create({
      data: {
        ownerId: owner.id,
        title: p.title,
        slug: p.slug,
        description: p.description,
        propertyType: p.propertyType,
        roomType: p.roomType,
        furnishing: p.furnishing,
        floor: p.floor,
        totalFloors: p.totalFloors,
        roomSizeSqft: p.roomSizeSqft,
        bathrooms: p.bathrooms,
        balconies: p.balconies,
        kitchenType: p.kitchenType,
        parkingType: p.parkingType,
        rentMonthly: p.rentMonthly,
        deposit: p.deposit,
        maintenanceCharges: p.maintenanceCharges,
        electricityIncluded: p.electricityIncluded,
        waterIncluded: p.waterIncluded,
        foodIncluded: p.foodIncluded,
        genderPreference: p.genderPreference,
        tenantPreference: p.tenantPreference,
        country: p.country,
        state: p.state,
        city: p.city,
        area: p.area,
        address: p.address,
        landmark: p.landmark,
        latitude: p.latitude,
        longitude: p.longitude,
        distanceToHub: p.distanceToHub,
        status: p.status,
        isVerified: p.isVerified,
        featured: p.featured,
        noBrokerage: p.noBrokerage,
        viewsCount: Math.floor(Math.random() * 450) + 50,
        favoritesCount: Math.floor(Math.random() * 60) + 10,
        images: {
          create: p.images.map((url, idx) => ({
            url,
            isCover: idx === 0,
            displayOrder: idx,
            caption: idx === 0 ? 'Main Room View' : `Room Interior ${idx + 1}`,
          })),
        },
        amenities: {
          create: p.amenities.map(a => ({
            name: a.name,
            category: a.category,
            iconKey: a.iconKey,
          })),
        },
        rules: {
          create: p.rules.map(r => ({
            ruleText: r.ruleText,
            ruleType: r.ruleType,
          })),
        },
      },
    });
    createdProperties.push(property);
  }

  // 5. Create Sample Bookings & Payments
  const firstProperty = createdProperties[0];
  const secondProperty = createdProperties[1];
  const firstTenant = tenants[0];
  const secondTenant = tenants[1];

  // Confirmed booking with successful payment
  const booking1 = await prisma.booking.create({
    data: {
      propertyId: firstProperty.id,
      tenantId: firstTenant.id,
      status: 'CONFIRMED',
      moveInDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
      stayMonths: 6,
      occupantsCount: 1,
      tenantMessage: 'Hi Rajesh ji, looking forward to moving in. I am a software engineer working hybrid.',
      ownerNotes: 'Accepted. Sent tenancy draft agreement.',
      monthlyRent: firstProperty.rentMonthly,
      depositAmount: firstProperty.deposit,
      maintenanceAmount: firstProperty.maintenanceCharges,
      platformFee: 299,
      taxesAmount: 54,
      totalAmount: firstProperty.rentMonthly + firstProperty.deposit + firstProperty.maintenanceCharges + 299 + 54,
      paidAmount: firstProperty.rentMonthly + firstProperty.deposit + firstProperty.maintenanceCharges + 299 + 54,
      payment: {
        create: {
          razorpayOrderId: 'order_test_901234',
          razorpayPaymentId: 'pay_test_881920',
          razorpaySignature: 'simulated_valid_signature',
          amount: (firstProperty.rentMonthly + firstProperty.deposit + firstProperty.maintenanceCharges + 299 + 54) * 100,
          status: 'SUCCESS',
          receiptUrl: '/receipts/sample-receipt-001.pdf',
        },
      },
    },
  });

  // Pending inquiry / requested booking for testing Owner Dashboard
  const booking2 = await prisma.booking.create({
    data: {
      propertyId: firstProperty.id,
      tenantId: secondTenant.id,
      status: 'REQUESTED',
      moveInDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
      stayMonths: 3,
      occupantsCount: 1,
      tenantMessage: 'Hello! I am a student at AU Arts faculty. Is this room available from next Monday?',
      monthlyRent: firstProperty.rentMonthly,
      depositAmount: firstProperty.deposit,
      maintenanceAmount: firstProperty.maintenanceCharges,
      platformFee: 299,
      taxesAmount: 54,
      totalAmount: firstProperty.rentMonthly + firstProperty.deposit + firstProperty.maintenanceCharges + 299 + 54,
    },
  });

  // 6. Create Authentic Reviews
  await prisma.review.create({
    data: {
      propertyId: firstProperty.id,
      tenantId: firstTenant.id,
      bookingId: booking1.id,
      ratingOverall: 4.9,
      ratingCleanliness: 5.0,
      ratingLocation: 5.0,
      ratingAmenities: 4.8,
      ratingOwner: 5.0,
      comment: 'Super peaceful stay! Rajesh ji was extremely helpful from day one. High speed WiFi never dropped during my zoom meetings and the room was sparkling clean.',
      ownerReply: 'Thank you Rahul! You were a fantastic tenant and kept the place in pristine condition. Always welcome!',
    },
  });

  await prisma.review.create({
    data: {
      propertyId: secondProperty.id,
      tenantId: tenants[2].id,
      ratingOverall: 4.8,
      ratingCleanliness: 4.7,
      ratingLocation: 5.0,
      ratingAmenities: 4.8,
      ratingOwner: 4.9,
      comment: 'Great value for students. The food quality is authentic home style, and Anand Bhawan library is just a short stroll away. Highly recommended for UPSC aspirants.',
      ownerReply: 'Glad you liked the food and atmosphere Aditya! Best of luck for your upcoming exams.',
    },
  });

  // 7. Create Favorites for Rahul (tenant 0)
  await prisma.favorite.create({
    data: {
      userId: firstTenant.id,
      propertyId: firstProperty.id,
    },
  });
  await prisma.favorite.create({
    data: {
      userId: firstTenant.id,
      propertyId: createdProperties[4].id, // Koramangala studio
    },
  });

  // 8. Create Sample Conversation & Messages
  const conversation = await prisma.conversation.create({
    data: {
      propertyId: firstProperty.id,
      participant1Id: firstTenant.id,
      participant2Id: owners[0].id,
      messages: {
        create: [
          {
            senderId: firstTenant.id,
            content: 'Hello Rajesh ji, is car parking also possible for occasional weekend visitors?',
            readStatus: true,
          },
          {
            senderId: owners[0].id,
            content: 'Namaste Rahul! Yes, we have street parking with CCTV coverage right outside our main gate.',
            readStatus: true,
          },
        ],
      },
    },
  });

  // 9. Create Notifications
  await prisma.notification.create({
    data: {
      userId: owners[0].id,
      title: 'New Booking Inquiry',
      message: 'Sneha Patel requested to book your room in Civil Lines, Prayagraj.',
      type: 'BOOKING_REQUEST',
      link: '/owner/dashboard',
      isRead: false,
    },
  });

  await prisma.notification.create({
    data: {
      userId: firstTenant.id,
      title: 'Booking Confirmed!',
      message: 'Your stay at Modern Single Room in Civil Lines has been confirmed by owner Rajesh Mehra.',
      type: 'BOOKING_ACCEPTED',
      link: '/dashboard',
      isRead: false,
    },
  });

  console.log('Seeding completed successfully!');
}

main()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
